# Generated by Django 2.0.6 on 2019-04-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netdev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='netdev',
            name='condition',
            field=models.CharField(default=None, max_length=100, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='netdev',
            name='sp',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling price'),
        ),
    ]
