# Generated by Django 2.0.6 on 2019-05-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netdev', '0002_auto_20190407_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netdev',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='netdev',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='netdev',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='netdev',
            name='generation',
            field=models.CharField(blank=True, max_length=5, verbose_name='Generation'),
        ),
        migrations.AlterField(
            model_name='netdev',
            name='other',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='netdev',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, verbose_name='Warranty status'),
        ),
    ]
