# Generated by Django 2.0.6 on 2019-05-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='server',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='server',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='server',
            name='os',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Operating system'),
        ),
        migrations.AlterField(
            model_name='server',
            name='other',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='server',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, verbose_name='Warranty status'),
        ),
    ]
